apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: spin
    stack: gate
  name: spin-gate
  namespace: spinnaker
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.217.68.121
  ports:
  - name: http
    port: 8084
    protocol: TCP
    targetPort: 8084
  - name: monitoring
    port: 8008
    protocol: TCP
    targetPort: 8008
  selector:
    load-balancer-spin-gate: "true"
  sessionAffinity: None
  type: LoadBalancer

