---
kind: Service
apiVersion: v1
metadata:
  name: spin-gate
  namespace: spinnaker-devops
  labels:
    app: spin
    stack: gate
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8084
    targetPort: 8084
  - name: monitoring
    protocol: TCP
    port: 8008
    targetPort: 8008
  type: LoadBalancer
  selector:
    load-balancer-spin-gate: "true"
    

