kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
spec:
  storageClassName: managed-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  

