schema: "1"
id: SpringBatchProdCDTemplateV1
metadata:
  name: Spring Batch Prod CD Template - Develop Branch
  description: Spring Batch Prod Continuous Delivery Pipeline Template - Develop Branch
  owner: digital-ms-devops@walgreens.com
  scopes: [global]
variables:
- name: microserviceName
  description: Name of the Microservice
- name: TeamName
  description: Enter Your Team Name
  example: Devops
  defaultValue: Devops    
- name: TeamDL
  description: Enter Your Team DL
  example: ecomscm@walgreens.com
configuration:
  concurrentExecutions:
    limitConcurrent: true
    parallel: false
  triggers:
  - account: dotcomprodregistry
    enabled: true
    name: unnamed0
    organization: digital/dotcom
    registry: wagdigitaldotcomprod.azurecr.io
    repository: digital/dotcom/{{ microserviceName }}
    runAsUser: spinnaker-svc-account
    status:
    - successful
    tag: ".*"
    type: docker
  parameters: []
  notifications: []
  description: ""
stages:
- id: ProceedToProd
  type: manualJudgment
  name: RMApproval
  config:
    failPipeline: true
    instructions: "Proceed Build #${trigger['tag']} to Prod?"
    judgmentInputs: []
    notifications:
    - address: "{{ TeamDL }}"
      level: stage
      type: email
      when:
      - manualJudgment
      - manualJudgmentContinue
      - manualJudgmentStop
    sendNotifications: true
    propagateAuthenticationContext: false
- id: configureProd
  type: jenkins
  name: Configure Prod
  dependsOn:
  - ProceedToProd
  config:
    continuePipeline: false
    failPipeline: true
    job: "{{ microserviceName }}/job/{{ microserviceName }}-configmap-prod"
    master: intopsprd-jenkins
    parameters: {}
- id: deployToProd
  type: jenkins
  name: Deploy to Prod
  dependsOn:
  - configureProd
  config:
    notifications:
    - address: "{{ TeamDL }}"
      level: stage
      type: email
      when:
      - stage.failed
    sendNotifications: true
    continuePipeline: false
    failPipeline: true
    job: "{{ microserviceName }}/job/{{ microserviceName }}-deploy-prod"
    master: intopsprd-jenkins
    parameters: {
    "buildnumber": "${trigger['tag']}"
    }

