schema: "1"
id: SpringBatchQA3ManualJobRunTemplateV1
metadata:
  name: Spring Batch Manual Job Run - QA3
  description: Spring Batch Manual Job Run Pipeline Template - QA3
  owner: digital-ms-devops@walgreens.com
  scopes: [global]
variables:
- name: microserviceName
  description: Name of the Microservice
- name: TeamName
  description: Enter Your Team Name
  example: Devops
  defaultValue: Devops  
- name: TeamDL
  description: Enter Your Team DL
  example: ecomscm@walgreens.com
configuration:
  concurrentExecutions:
    limitConcurrent: true
    parallel: false
  triggers: []
  parameters: []
  notifications: []
  description: ""
stages:
- id: manualJobRunQA3
  type: jenkins
  name: Run Cronjob QA3
  config:
    continuePipeline: false
    failPipeline: true
    job: "{{ microserviceName }}/job/{{ microserviceName }}-manualjobrun-QA3"
    master: intops-jenkins
    parameters: {}

