schema: "1"
id: SpringBatchQA3CDTemplateV1
metadata:
  name: Spring Batch QA3 CD Template - Feature Branch
  description: Spring Batch QA3 Continuous Delivery Pipeline Template - Feature Branch
  owner: digital-ms-devops@walgreens.com
  scopes: [global]
variables:
- name: microserviceName
  description: Name of the Microservice
- name: TeamName
  description: Enter Your Team Name
  example: Devops
  defaultValue: Devops  
- name: TeamDL
  description: Enter Your Team DL
  example: ecomscm@walgreens.com
configuration:
  concurrentExecutions:
    limitConcurrent: true
    parallel: false
  triggers:
  - account: nonprodregistry
    enabled: true
    name: unnamed0
    organization: digital/dotcom
    registry: nonprodregistry.azurecr.io
    repository: digital/dotcom/{{ microserviceName }}
    runAsUser: spinnaker-svc-account
    status:
    - successful
    tag: ".*"
    type: docker
  parameters: []
  notifications: []
  description: ""
stages:
- id: configureQA3
  type: jenkins
  name: Configure QA3
  config:
    continuePipeline: false
    failPipeline: true
    job: "{{ microserviceName }}/job/{{ microserviceName }}-configmap-qa3-feature"
    master: intops-jenkins
    parameters: {}
- id: deployToQA3
  type: jenkins
  name: Deploy to QA3
  dependsOn:
  - configureQA3
  config:
    notifications:
    - address: "{{ TeamDL }}"
      level: stage
      type: email
      when:
      - stage.failed
    sendNotifications: true
    continuePipeline: false
    failPipeline: true
    job: "{{ microserviceName }}/job/{{ microserviceName }}-deploy-qa3-feature"
    master: intops-jenkins
    parameters: {
    "buildnumber": "${trigger['tag']}"
    }

